"""empty message

Revision ID: dab723dc009e
Revises: 5898fa0e9910
Create Date: 2024-10-12 17:59:29.750219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab723dc009e'
down_revision = '5898fa0e9910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('thumbnail_image', sa.String(length=255), nullable=False),
    sa.Column('other_images', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('class_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('listing')
    # ### end Alembic commands ###
